# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrea-batazzi/dev/lab/2025/mod_audio_stream

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrea-batazzi/dev/lab/2025/mod_audio_stream

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/andrea-batazzi/dev/lab/2025/mod_audio_stream/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"changelog.gz\" \"copyright\" \"mod_audio_stream\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea-batazzi/dev/lab/2025/mod_audio_stream/CMakeFiles /home/andrea-batazzi/dev/lab/2025/mod_audio_stream//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea-batazzi/dev/lab/2025/mod_audio_stream/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mod_audio_stream

# Build rule for target.
mod_audio_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mod_audio_stream
.PHONY : mod_audio_stream

# fast build rule for target.
mod_audio_stream/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/build
.PHONY : mod_audio_stream/fast

#=============================================================================
# Target rules for targets named changelog_target

# Build rule for target.
changelog_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 changelog_target
.PHONY : changelog_target

# fast build rule for target.
changelog_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/changelog_target.dir/build.make CMakeFiles/changelog_target.dir/build
.PHONY : changelog_target/fast

#=============================================================================
# Target rules for targets named copyright_target

# Build rule for target.
copyright_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copyright_target
.PHONY : copyright_target

# fast build rule for target.
copyright_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copyright_target.dir/build.make CMakeFiles/copyright_target.dir/build
.PHONY : copyright_target/fast

#=============================================================================
# Target rules for targets named libwsc

# Build rule for target.
libwsc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libwsc
.PHONY : libwsc

# fast build rule for target.
libwsc/fast:
	$(MAKE) $(MAKESILENT) -f libs/libwsc/CMakeFiles/libwsc.dir/build.make libs/libwsc/CMakeFiles/libwsc.dir/build
.PHONY : libwsc/fast

audio_streamer_glue.o: audio_streamer_glue.cpp.o
.PHONY : audio_streamer_glue.o

# target to build an object file
audio_streamer_glue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/audio_streamer_glue.cpp.o
.PHONY : audio_streamer_glue.cpp.o

audio_streamer_glue.i: audio_streamer_glue.cpp.i
.PHONY : audio_streamer_glue.i

# target to preprocess a source file
audio_streamer_glue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/audio_streamer_glue.cpp.i
.PHONY : audio_streamer_glue.cpp.i

audio_streamer_glue.s: audio_streamer_glue.cpp.s
.PHONY : audio_streamer_glue.s

# target to generate assembly for a file
audio_streamer_glue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/audio_streamer_glue.cpp.s
.PHONY : audio_streamer_glue.cpp.s

base64.o: base64.cpp.o
.PHONY : base64.o

# target to build an object file
base64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/base64.cpp.o
.PHONY : base64.cpp.o

base64.i: base64.cpp.i
.PHONY : base64.i

# target to preprocess a source file
base64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/base64.cpp.i
.PHONY : base64.cpp.i

base64.s: base64.cpp.s
.PHONY : base64.s

# target to generate assembly for a file
base64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/base64.cpp.s
.PHONY : base64.cpp.s

mod_audio_stream.o: mod_audio_stream.c.o
.PHONY : mod_audio_stream.o

# target to build an object file
mod_audio_stream.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/mod_audio_stream.c.o
.PHONY : mod_audio_stream.c.o

mod_audio_stream.i: mod_audio_stream.c.i
.PHONY : mod_audio_stream.i

# target to preprocess a source file
mod_audio_stream.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/mod_audio_stream.c.i
.PHONY : mod_audio_stream.c.i

mod_audio_stream.s: mod_audio_stream.c.s
.PHONY : mod_audio_stream.s

# target to generate assembly for a file
mod_audio_stream.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mod_audio_stream.dir/build.make CMakeFiles/mod_audio_stream.dir/mod_audio_stream.c.s
.PHONY : mod_audio_stream.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... changelog_target"
	@echo "... copyright_target"
	@echo "... libwsc"
	@echo "... mod_audio_stream"
	@echo "... audio_streamer_glue.o"
	@echo "... audio_streamer_glue.i"
	@echo "... audio_streamer_glue.s"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... mod_audio_stream.o"
	@echo "... mod_audio_stream.i"
	@echo "... mod_audio_stream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

